version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - python-executor

  python-executor:
    image: python:3.11-slim
    volumes:
      - ./backend/python-executor:/app
    working_dir: /app
    command: tail -f /dev/null
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"